# -*- coding: utf-8 -*-
"""CAESAR_IMPLEMENTATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQLWXBovsbz3f3Zq3sKlj9dMmzLwa8nn

# CAESAR CIPHER IMPLEMENTATION
Julian David Osoo Amaya

## Caesar cipher class
"""

class Caesar:
  def __init__(self, permutations):
    self.permutations = permutations

  @staticmethod
  def normal_input(text):
    return text.lower()

  def encrypt(self, message):
    enc_message = ""
    for char in message:
      if char.isalpha():
        enc_message += chr((ord(char) + self.permutations - 97) % 26 + 97)
    return enc_message

  def decrypt(self, message):
    dec_message = ""
    for char in message:
      if char.isalpha():
        dec_message += chr((ord(char) - self.permutations - 97) % 26 + 97)
    return dec_message

  def compute(self, option, message):
    if option == 0:
      return self.encrypt(self.normal_input(message))
    elif option == 1:
      return self.decrypt(self.normal_input(message))

"""## Test"""

plain_text = input("Enter the plain text: ")
k = int(input("Enter the number of permutations for the encryption: "))
caesar = Caesar(k)

enc_text = caesar.compute(0, plain_text)
print(f"The encrypted message is: {enc_text}")

dec_text = caesar.compute(1, enc_text)
print(f"The decrypted message is: {dec_text}")